config/routes.rb
Rails.application.routes.draw do
  resources :schools
  root 'courses#index'
  resources :user_courses
  devise_for :users
  resources :user_courses
  resources :courses

  resources :schools do
    resources :courses, :shallow => true
  end

end

app/controllers/user_courses_controller.rb
class UserCoursesController < ApplicationController
  before_action :set_user_course, only: [:show, :edit, :update, :destroy]

  # GET /user_courses
  # GET /user_courses.json
  def index
    @user_courses = UserCourse.all
  end

  # GET /user_courses/1
  # GET /user_courses/1.json
  def show
  end

  # GET /user_courses/new
  def new
    @user_course = UserCourse.new
  end

  # GET /user_courses/1/edit
  def edit
  end

  # POST /user_courses
  # POST /user_courses.json
  def create
    @user_course = UserCourse.new(user_course_params)

    respond_to do |format|
      if @user_course.save
        format.html { redirect_to course_path(@user_course.course_id), notice: 'User course was successfully created.' }
        format.json { render :show, status: :created, location: @user_course }
      else
        format.html { render :new }
        format.json { render json: @user_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_courses/1
  # PATCH/PUT /user_courses/1.json
  def update
    respond_to do |format|
      if @user_course.update(user_course_params)
        format.html { redirect_to @user_course, notice: 'User course was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_course }
      else
        format.html { render :edit }
        format.json { render json: @user_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_courses/1
  # DELETE /user_courses/1.json
  def destroy
    @user_course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'User course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_course
      @user_course = UserCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_course_params
      params.require(:user_course).permit(:user_id, :course_id)
    end
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/views/user_courses/_form.html.erb
<%= form_for(@user_course) do |f| %>
  <% if @user_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_course.errors.count, "error") %> prohibited this user_course from being saved:</h2>

      <ul>
      <% @user_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_courses/edit.html.erb
<h1>Editing User Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_course %> |
<%= link_to 'Back', user_courses_path %>

app/views/user_courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Courses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_courses.each do |user_course| %>
      <tr>
        <td><%= user_course.user_id %></td>
        <td><%= user_course.course_id %></td>
        <td><%= link_to 'Show', user_course %></td>
        <td><%= link_to 'Edit', edit_user_course_path(user_course) %></td>
        <td><%= link_to 'Destroy', user_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User course', new_user_course_path %>

app/views/user_courses/new.html.erb
<h1>New User Course</h1>

<%= render 'form' %>

<%= link_to 'Back', user_courses_path %>

app/views/user_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_course.user_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @user_course.course_id %>
</p>

<%= link_to 'Edit', edit_user_course_path(@user_course) %> |
<%= link_to 'Back', user_courses_path %>