config/routes.rb
Rails.application.routes.draw do
  resources :schools
  root 'courses#index'
  resources :user_courses
  devise_for :users
  resources :user_courses
  resources :courses

  resources :schools do
    resources :courses, :shallow => true
  end

end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :courses, dependent: :destroy
  has_many :users 
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @courses = Course.all
    @course = Course.new
   end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :domain)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.haml
%div.opaque-back.container-fluid
  %ul{:class => "nav nav-tabs"}
    %li= link_to 'courses', courses_url
    %li{:class => "active"}= link_to 'Schools', schools_url 
    %li= link_to "Sign out", destroy_user_session_path, method: :delete

  %h1 Listing Schools
  %table.table.table-bordered.container-fluid
    %thead
      %tr
        %td Name
        %td{:colspan => "2"} Options
    %tbody
      - @schools.each do |school|
        %tr
          %td= link_to school.name, school
          %td= link_to 'Edit', edit_school_path(school)
          %td= link_to 'Destroy', school, method: :delete, data: { confirm: '    Are you sure?' }
  %br
  %div{:style => "padding-bottom: 15px;"}
    = button_to 'New School', new_school_path
    = button_to 'Courses', courses_url

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.haml
%div.opaque-back.container-fluid
  %ul.nav.nav-tabs
    %li= link_to 'courses', courses_url
    %li.active= link_to 'Schools', schools_url 
    %li= link_to "Sign out", destroy_user_session_path, method: :delete

  %p
    %h1= @school.name
  %table.table.table-bordered.container-fluid
    %thead 
      %tr
        %td Name
        %td{:colspan => "2"} Options
    %tbody
      - @courses.each do |course|
        - if course.school_id == @school.id
          %tr
            %td= link_to course.name, course
            %td= link_to 'Edit', edit_course_path(course)
            %td= link_to 'Destroy', course, method: :delete, data: { confirm: '    Are you sure?' }

  %p
    %strong New Course:
    = form_for @course do |f|
      .field
        = f.label :name
        %b
        = f.text_field :name
      .field
        = f.label :number
        %b
        = f.number_field :number
      = f.hidden_field :school_id, :value => @school.id
      .action
        = f.submit