config/routes.rb
Rails.application.routes.draw do
  resources :schools
  root 'courses#index'
  resources :user_courses
  devise_for :users
  resources :user_courses
  resources :courses

  resources :schools do
    resources :courses, :shallow => true
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /co
  # GET /courses.json
  def index
    @courses = Course.all
    @user_courses = UserCourse.all
    @users = coursesNotIn
    @schools = School.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @courses = Course.all
    @user_courses = UserCourse.all
    @users = coursesNotIn
    @user_course = UserCourse.new
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end
  
  def email_user(to, course)
    sendmail( :to => to.email,
    :subject => 'You\'ve been pinged') 
  end
  helper_method :email_user

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to schools_url(@course.school_id), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to schools_url(@course.school_id), notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :number, :school_id)
    end

    def coursesIn
      users = User.all
      userCourses = UserCourse.all
      courses = Course.all
      userCourses.each do |userCourse|
        courses.each do |course|
          users.each do |user|
            if course.id == userCourse.course_id && user.id == userCourse.user_id
              user.coursesIn.push(course)
            end
          end
        end
      end
      return users
    end
    def coursesNotIn
      courses = Course.all
      users = coursesIn
      schools = School.all
      users.each do |user|
        schools.each do |school|
          if user.domain == school.domain
            courses.each do |course|
              if course.school_id == school.id && !user.coursesIn.include?(course)
                user.coursesNotIn.push(course)
              end
            end
          end
        end
      end
      return users
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.haml
%p{:class => "notice"}= notice
= form_for(@course) do |f|
  - if @course.errors.any?
    #content
      %h2
        = pluralize(@course.errors.count, "error")
        prohibited this course from being saved:
      %ul
      - @course.errors.full_messages.each do |message|
        %li= message
  .field  
    = f.label :name
    %br
    = f.text_field :name
  
  .field
    = f.label :number
    %br
    = f.number_field :number

  .feild
    = f.label :school_id
    %br
    = f.number_field :school_id

  .actions
    = f.submit

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.haml
%body
  %div.opaque-back.container-fluid
    %ul.nav.nav-tabs
      %li.dropdown.active
        =link_to "Courses", courses_url
        %ul#menu1.dropdown-menu
          %li
            %a{:href => "#"}
              Courses Im IN
            %ul.dropdown-menu.sub-menu
              - @users.each do |user|
                - if user.id == current_user.id
                  - user.coursesIn.each do |courseIn|
                    %li= link_to courseIn.name, courseIn
          %li.divider
          %li
            %a{:href => "#"}
              Other Courses
            %ul.dropdown-menu.sub-menu
              - @users.each do |user|
                - if user.id == current_user.id
                  - user.coursesNotIn.each do |courseNotIn|
                    %li= link_to courseNotIn.name, courseNotIn

      %li= link_to 'Schools', schools_url 
      %li= link_to "Sign out", destroy_user_session_path, method: :delete


    %strong Courses You're in:
    %br
    %table.table.table-bordered.container-fluid.opaque-back
      %thead
        %tr
          %td Course name:
          %td Course number:
          %td School:
      %tbody
        - @users.each do |user|
          - if user.id == current_user.id
            - user.coursesIn.each do |course|
              %tr
                %td= link_to course.name, course
                %td= course.number
                - @schools.each do |school|
                  - if course.school_id == school.id
                    %td= school.name
    %br
    %strong Other courses in the University:
    %br
    %table{:class => "container-fluid table table-bordered"}
      %thead
        %tr
          %td Course name:
          %td Course number:
          %td School:
      %tbody
        - @users.each do |user|
          - if user.id == current_user.id
            - user.coursesNotIn.each do |course|
              %tr
                %td= link_to course.name, course
                %td= course.number
                - @schools.each do |school|
                  - if course.school_id == school.id && school.domain == current_user.domain
                    %td= school.name

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.haml
%div.opaque-back.container-fluid
  %ul.nav.nav-tabs
    %li.dropdown.active
      =link_to "Courses", courses_url
      %ul#menu1.dropdown-menu
        %li
          %a{:href => "#"}
            Courses Your In
          %ul.dropdown-menu.sub-menu
            - @users.each do |user|
              - if user.id == current_user.id
                - user.coursesIn.each do |courseIn|
                  - if courseIn.id == @course.id
                    %li.active= link_to courseIn.name, courseIn
                  - else
                    %li= link_to courseIn.name, courseIn
        %li.divider
        %li
          %a{:href => "#"}
            Other Courses
          %ul.dropdown-menu.sub-menu
            - @users.each do |user|
              - if user.id == current_user.id
                - user.coursesNotIn.each do |courseNotIn|
                  - if courseNotIn.id == @course.id
                    %li.active= link_to courseNotIn.name, courseNotIn
                  - else
                    %li= link_to courseNotIn.name, courseNotIn
    %li= link_to 'Schools', schools_url 
    %li= link_to "Sign out", destroy_user_session_path, method: :delete

  %h1= @course.name
  - @users.each do |myuser|
    - if myuser.coursesIn.include?(@course) && myuser.id == current_user.id
    
      %strong Other students in this course:
      %br
      %table.container-fluid.table.table-bordered
        %tbody
          - @user_courses.each do |user_course|
            - if user_course.course_id == @course.id
              - @users.each do |user|
                - if user_course.user_id == user.id
                  %tr
                    %td= user.name
                    %td= link_to 'E-Mail'
      - @user_courses.each do |user_course|
        - if user_course.course_id == @course.id && user_course.user_id == current_user.id
          = button_to 'Drop Course'
    - elsif !myuser.coursesIn.include?(@course) && myuser.id == current_user.id
      %strong Would you like to add this course?
      = form_for(@user_course) do |f|
        = f.hidden_field :user_id, :value => current_user.id
        = f.hidden_field :course_id, :value => @course.id
        %br
        %div{:style => "padding-bottom: 15px;"}
          = f.submit "Join Course"